epochs: 2000
beta: 0.001
learning_rate: 1.0

optimizer:
  name: SGD
  kwargs: {}

beta_scheduler: 
  name: null

lr_scheduler:
  name: CosineAnnealingWarmRestarts
  kwargs:
    eta_min: 10.0

budget: 70.0
